export const STYLE_EVENT = "STYLE_EVENT";
export const SHIRT_COLOUR_EVENT = "SHIRT_COLOUR_EVENT";
export const GRAPHICS_EVENT = "GRAPHICS_EVENT";
export const GRAPHICS_COLOR_EVENT = "GRAPHICS_COLOR_EVENT";
export const TEXT_EVENT = "TEXT_EVENT";
export const TEXT_COLOR_EVENT = "TEXT_COLOR_EVENT";
export const TEXT_FONT_EVENT= "TEXT_FONT_EVENT";

